# Use root/example as user/password credentials
version: '3.1'

services:
  measurmentappv2:
    image: webdevops/php-nginx:7.4
    restart: always
    ports:
      - 83:80
    volumes:
      - ./appcode:/app
      # /etc/mysql/mariadb.conf.d/50-server.cnf