# Use root/example as user/password credentials
version: '3.1'

services:
  measurmentapp:
    image: webdevops/php-apache:7.4
    restart: always
    environment:
      PHP_DISPLAY_ERRORS: 1
    ports:
      - 82:80
    volumes:
      - ./appcode:/app
      # /etc/mysql/mariadb.conf.d/50-server.cnf